apiVersion: v1
kind: Service
metadata:
  name: photo-memories-service
  namespace: photomemories
spec:
  selector:
    app: photo-memories
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP